### ISSUE TITLE
Audiocut does not work on Jolla C2, SFOS 5.0.0.43

### ISSUE THREAD

**Issue by eson57** [poetaster/harbour-audiocut#11]
I was thinking I should use this app, and was surprised that launching from app drawer gave only a white screen. Trying Fingerterm just said 'Could not find harbour-audiocut'... even more surprising if you ask me. 
I have no idea how to troubleshoot furthermore. 

Edit:
The one from OpenRepos seem to work fine. My previous attempt was installed from Chum.

Edit2:
Wrong again. The one from OpenRepos doesn't work either, but at least I got to see a GUI. Admittedly useless, but still a GUI.

**Comment by poetaster** [comment]
Hmmm. Strange. I'll try re-installing from chum. 

What version of SFOS and on which device are you using?

**Comment by eson57** [comment]
As in topic, Jolla C2, SFOS 5.0.0.43.  ;-)

**Comment by eson57** [comment]
I did a quick check on my X10III with latest SFOS 4.6 and yes, same behaviour on the one from Chum, white screen. The one from OpenRepos seem to work as intended.

**Comment by poetaster** [comment]
I found the issue on the versions that were last posted. A bit strange. I'm bumping this version so that github, openrepos and chum are all in  sync again. Should be available in an hour or two. Chum could take a day.

**Comment by poetaster** [comment]
The version published here on github and the openrepos version should work now. It will take a day or two to get to chum.

**Comment by eson57** [comment]
Thanks, but it still don't work on my C2. App doesn't import my files (wav). There is just the spinning wheel and nothing more. And what more is...
```
defaultuser@JollaC2 ~]$ harbour-audiocut
/bin/bash: harbour-audiocut: not found
[defaultuser@JollaC2 ~]$
```

**Comment by poetaster** [comment]
> Thanks, but it still don't work on my C2. App doesn't import my my files (wav). There is just the spinning weel and nothing more. And what more is...
> 
> ```
> defaultuser@JollaC2 ~]$ harbour-audiocut
> /bin/bash: harbour-audiocut: not found
> [defaultuser@JollaC2 ~]$
> ```

from here? or from open repos?

**Comment by eson57** [comment]
From OpenRepos

**Comment by poetaster** [comment]
> From OpenRepos

Hmmm. I just tested that and it's fine. Could you run from the terminal and let me know? The way to run it is:

# sailfish-qml harbour-audiocut

**Comment by eson57** [comment]
Ahaa...I didn't know about _sailfish-qml_.

Here's the vey long log...

```
[defaultuser@JollaC2 ~]$ sailfish-qml harbour-audiocut
[D] unknown:0 - Using Wayland-EGL
library "libutils.so" not found
library "libdmabufheap.so" not found
library "libbase.so" not found
library "libz.so" not found
library "libcutils.so" not found
library "android.hardware.graphics.mapper@4.0.so" not found
library "libgralloctypes.so" not found
library "libhidlbase.so" not found
library "libhardware.so" not found
library "libc++.so" not found

(process:2794): dconf-CRITICAL **: 11:48:59.808: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.813: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.815: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.818: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.819: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.822: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.823: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.826: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.827: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.828: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.831: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.832: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.833: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.833: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.834: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.834: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.835: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.835: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.836: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.837: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.840: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.841: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.841: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.843: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.844: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.844: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.845: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.845: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.846: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.847: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.848: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.851: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.851: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.852: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.853: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.854: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.855: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.856: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.859: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.860: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.860: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.861: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.862: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.863: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.865: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.868: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.869: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.871: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.873: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.875: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.876: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.879: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.880: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.882: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.883: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.886: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.887: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.889: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.891: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.893: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.896: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.897: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.899: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.902: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.902: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.904: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.908: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.908: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.910: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.913: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.913: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.914: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.917: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.919: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.920: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.924: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.925: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.927: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.929: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.930: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.932: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.934: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.935: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.936: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.938: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.939: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.940: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.943: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.944: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.945: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.947: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.948: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.950: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.951: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.953: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.955: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.956: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.958: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.959: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.960: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.962: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.963: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.964: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.966: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.967: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.968: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.971: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.973: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.974: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.977: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.978: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.980: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.983: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.984: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.985: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.988: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.990: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.991: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.994: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.996: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.996: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:48:59.998: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:49:00.002: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:49:00.010: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:49:00.012: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:49:00.013: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:49:00.016: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:49:00.017: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:49:00.017: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:49:00.021: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:49:00.021: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:49:00.023: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:49:00.025: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:49:00.026: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:49:00.027: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:49:00.029: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:49:00.032: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:49:00.033: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:49:00.038: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:49:00.039: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:49:00.042: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:49:00.044: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:49:00.047: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:49:00.049: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:49:00.052: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:49:00.054: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:49:00.056: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:49:00.057: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:49:00.058: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:49:00.058: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:49:00.060: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:49:00.060: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:49:00.062: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:49:00.063: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:49:00.064: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:49:00.065: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:49:00.066: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:49:00.066: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:49:00.068: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:49:00.069: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:49:00.072: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:49:00.072: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:49:00.074: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:49:00.075: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:49:00.077: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:49:00.079: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:49:00.083: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:49:00.084: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.
[D] unknown:0 - Got library name:  "/usr/lib64/qt5/qml/io/thp/pyotherside/libpyothersideplugin.so"

(process:2794): dconf-CRITICAL **: 11:49:00.935: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:49:00.940: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:49:00.941: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:49:00.943: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:49:00.946: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:49:00.951: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:49:00.969: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:49:00.973: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:49:00.974: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:49:00.977: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:49:00.977: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(process:2794): dconf-CRITICAL **: 11:49:00.984: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(sailfish-qml:2794): dconf-CRITICAL **: 11:49:01.052: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(sailfish-qml:2794): dconf-CRITICAL **: 11:49:01.056: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(sailfish-qml:2794): dconf-CRITICAL **: 11:49:01.059: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(sailfish-qml:2794): dconf-CRITICAL **: 11:49:01.060: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(sailfish-qml:2794): dconf-CRITICAL **: 11:49:01.064: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(sailfish-qml:2794): dconf-CRITICAL **: 11:49:01.069: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(sailfish-qml:2794): dconf-CRITICAL **: 11:49:01.411: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(sailfish-qml:2794): dconf-CRITICAL **: 11:49:01.416: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(sailfish-qml:2794): dconf-CRITICAL **: 11:49:01.417: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(sailfish-qml:2794): dconf-CRITICAL **: 11:49:01.420: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(sailfish-qml:2794): dconf-CRITICAL **: 11:49:01.422: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(sailfish-qml:2794): dconf-CRITICAL **: 11:49:01.428: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(sailfish-qml:2794): dconf-CRITICAL **: 11:49:01.429: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(sailfish-qml:2794): dconf-CRITICAL **: 11:49:01.434: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(sailfish-qml:2794): dconf-CRITICAL **: 11:49:01.439: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.
library "libion.so" not found
/usr/share/harbour-audiocut/lib/pydub/utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)

(sailfish-qml:2794): dconf-CRITICAL **: 11:49:01.748: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(sailfish-qml:2794): dconf-CRITICAL **: 11:49:01.753: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(sailfish-qml:2794): dconf-CRITICAL **: 11:49:01.755: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(sailfish-qml:2794): dconf-CRITICAL **: 11:49:01.757: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(sailfish-qml:2794): dconf-CRITICAL **: 11:49:01.758: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(sailfish-qml:2794): dconf-CRITICAL **: 11:49:01.759: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(sailfish-qml:2794): dconf-CRITICAL **: 11:49:01.761: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(sailfish-qml:2794): dconf-CRITICAL **: 11:49:01.761: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(sailfish-qml:2794): dconf-CRITICAL **: 11:49:01.763: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(sailfish-qml:2794): dconf-CRITICAL **: 11:49:01.764: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(sailfish-qml:2794): dconf-CRITICAL **: 11:49:01.767: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(sailfish-qml:2794): dconf-CRITICAL **: 11:49:01.769: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(sailfish-qml:2794): dconf-CRITICAL **: 11:49:01.770: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(sailfish-qml:2794): dconf-CRITICAL **: 11:49:01.771: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(sailfish-qml:2794): dconf-CRITICAL **: 11:49:01.772: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(sailfish-qml:2794): dconf-CRITICAL **: 11:49:01.773: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(sailfish-qml:2794): dconf-CRITICAL **: 11:49:01.774: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(sailfish-qml:2794): dconf-CRITICAL **: 11:49:01.774: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(sailfish-qml:2794): dconf-CRITICAL **: 11:49:01.775: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(sailfish-qml:2794): dconf-CRITICAL **: 11:49:01.776: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(sailfish-qml:2794): dconf-CRITICAL **: 11:49:01.777: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(sailfish-qml:2794): dconf-CRITICAL **: 11:49:01.778: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(sailfish-qml:2794): dconf-CRITICAL **: 11:49:01.779: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(sailfish-qml:2794): dconf-CRITICAL **: 11:49:01.780: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(sailfish-qml:2794): dconf-CRITICAL **: 11:49:01.781: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(sailfish-qml:2794): dconf-CRITICAL **: 11:49:01.782: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(sailfish-qml:2794): dconf-CRITICAL **: 11:49:01.783: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(sailfish-qml:2794): dconf-CRITICAL **: 11:49:01.784: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(sailfish-qml:2794): dconf-CRITICAL **: 11:49:01.785: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(sailfish-qml:2794): dconf-CRITICAL **: 11:49:01.788: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(sailfish-qml:2794): dconf-CRITICAL **: 11:49:01.790: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(sailfish-qml:2794): dconf-CRITICAL **: 11:49:01.792: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(sailfish-qml:2794): dconf-CRITICAL **: 11:49:01.793: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(sailfish-qml:2794): dconf-CRITICAL **: 11:49:01.795: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(sailfish-qml:2794): dconf-CRITICAL **: 11:49:01.797: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(sailfish-qml:2794): dconf-CRITICAL **: 11:49:01.799: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(sailfish-qml:2794): dconf-CRITICAL **: 11:49:10.704: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(sailfish-qml:2794): dconf-CRITICAL **: 11:49:10.713: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(sailfish-qml:2794): dconf-CRITICAL **: 11:49:10.719: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.

(sailfish-qml:2794): dconf-CRITICAL **: 11:49:10.787: unable to create file '/run/user/100000/dconf/user': Åtkomst nekas.  dconf will not work properly.
[D] clearMarkerPos:1682 - ToDo
[D] unknown:0 - "PyOtherSide error: Traceback (most recent call last):\n\n  File \"/usr/share/harbour-audiocut/qml/py/audiox.py\", line 174, in createWaveformImage\n    subprocess.run([ \"ffmpeg\", \"-hide_banner\", \"-y\", \"-i\", \"/\"+inputPathPy, \"-filter_complex\", stretch+\"showwavespic=s=\"+waveformPixelLength+\"x\"+waveformPixelHeight+\":colors=\"+waveformColor, \"-frames:v\", \"1\", \"/\"+outputWaveformPath ])\n\n  File \"/usr/lib64/python3.8/subprocess.py\", line 493, in run\n    with Popen(*popenargs, **kwargs) as process:\n\n  File \"/usr/lib64/python3.8/subprocess.py\", line 858, in __init__\n    self._execute_child(args, executable, preexec_fn, close_fds,\n\n  File \"/usr/lib64/python3.8/subprocess.py\", line 1720, in _execute_child\n    raise child_exception_type(errno_num, err_msg, err_filename)\n\nFileNotFoundError: [Errno 2] Filen eller katalogen finns inte: 'ffmpeg'\n"
[D] onError:427 - python error: Return value of PyObject call is NULL: Traceback (most recent call last):

  File "/usr/share/harbour-audiocut/qml/py/audiox.py", line 174, in createWaveformImage
    subprocess.run([ "ffmpeg", "-hide_banner", "-y", "-i", "/"+inputPathPy, "-filter_complex", stretch+"showwavespic=s="+waveformPixelLength+"x"+waveformPixelHeight+":colors="+waveformColor, "-frames:v", "1", "/"+outputWaveformPath ])

  File "/usr/lib64/python3.8/subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:

  File "/usr/lib64/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,

  File "/usr/lib64/python3.8/subprocess.py", line 1720, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)

FileNotFoundError: [Errno 2] Filen eller katalogen finns inte: 'ffmpeg'
```

**Comment by poetaster** [comment]
THAT is a lot of dconf errors. I wonder why. But that's not the issue. I think you may be missing ffmpeg

zypper in ffmpeg or use the chum app to install ffmpeg (and lame while you are at it).

**Comment by poetaster** [comment]
Ah, I think you can get rid of the dconf errors if you use the command  : sailfish-qml harbour-audiocut %u 

that %u passes the correct user flag. so don't run with devel-su, but just as your normal user.

**Comment by eson57** [comment]
The most important lines translated from Swedish.

```
[defaultuser@JollaC2 ~]$ devel-su zypper in ffmpeg
Password: 
Läser in förrådsdata...
Läser installerade paket...
'ffmpeg' is already installed.
No update candidate for 'ffmpeg-5.1.6+git1-1.10.3.jolla.aarch64'. Highest available version is already installed.
Översätter paketberoenden...
Nothing to do.
```
%u didn't help, btw.

**Comment by poetaster** [comment]
Ok, well together with the dconf errors that seem to have an issue with not being able to make files (?) the issue now is that the python object, which is calling ffmpeg, can't see to find ffmpeg.

Could you please try: 
devel-su vi /usr/share/harbour-audiocut/qml/py/audiox.py
and change line 174 so that the ffmpeg part:  
```subprocess.run([ "ffmpeg", ```
becomes
```subprocess.run([ "/usr/bin/ffmpeg", ```

**Comment by eson57** [comment]
```
[defaultuser@JollaC2 ~]$ sailfish-qml harbour-audiocut %u
[D] unknown:0 - Using Wayland-EGL
library "libutils.so" not found
library "libdmabufheap.so" not found
library "libbase.so" not found
library "libz.so" not found
library "libcutils.so" not found
library "android.hardware.graphics.mapper@4.0.so" not found
library "libgralloctypes.so" not found
library "libhidlbase.so" not found
library "libhardware.so" not found
library "libc++.so" not found
[D] unknown:0 - Got library name:  "/usr/lib64/qt5/qml/io/thp/pyotherside/libpyothersideplugin.so"
library "libion.so" not found
/usr/share/harbour-audiocut/lib/pydub/utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
[D] clearMarkerPos:1682 - ToDo
[D] unknown:0 - "PyOtherSide error: Traceback (most recent call last):\n\n  File \"/usr/share/harbour-audiocut/qml/py/audiox.py\", line 174, in createWaveformImage\n    subprocess.run([ \"/usr/bin/ffmpeg\", \"-hide_banner\", \"-y\", \"-i\", \"/\"+inputPathPy, \"-filter_complex\", stretch+\"showwavespic=s=\"+waveformPixelLength+\"x\"+waveformPixelHeight+\":colors=\"+waveformColor, \"-frames:v\", \"1\", \"/\"+outputWaveformPath ])\n\n  File \"/usr/lib64/python3.8/subprocess.py\", line 493, in run\n    with Popen(*popenargs, **kwargs) as process:\n\n  File \"/usr/lib64/python3.8/subprocess.py\", line 858, in __init__\n    self._execute_child(args, executable, preexec_fn, close_fds,\n\n  File \"/usr/lib64/python3.8/subprocess.py\", line 1720, in _execute_child\n    raise child_exception_type(errno_num, err_msg, err_filename)\n\nFileNotFoundError: [Errno 2] Filen eller katalogen finns inte: '/usr/bin/ffmpeg'\n"
[D] onError:427 - python error: Return value of PyObject call is NULL: Traceback (most recent call last):

  File "/usr/share/harbour-audiocut/qml/py/audiox.py", line 174, in createWaveformImage
    subprocess.run([ "/usr/bin/ffmpeg", "-hide_banner", "-y", "-i", "/"+inputPathPy, "-filter_complex", stretch+"showwavespic=s="+waveformPixelLength+"x"+waveformPixelHeight+":colors="+waveformColor, "-frames:v", "1", "/"+outputWaveformPath ])

  File "/usr/lib64/python3.8/subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:

  File "/usr/lib64/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,

  File "/usr/lib64/python3.8/subprocess.py", line 1720, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)

FileNotFoundError: [Errno 2] Filen eller katalogen finns inte: '/usr/bin/ffmpeg'
```

You know what... it isnt' there '/usr/bin/ffmpeg'. Can't find it with File Browser.

**Comment by eson57** [comment]
I don't remember... how can make terminal show output in English.

**Comment by poetaster** [comment]
> I don't remember... how can make terminal 

I believe you could use: 

export LC_ALL="en_US.UTF-8"
and possibly add
export LANG="en_US.UTF-8"


```You know what... it isnt' there '/usr/bin/ffmpeg'. Can't find it with File Browser.```
Ok, then it's actually not installed. So, try deleting the package and installing it again.

**Comment by eson57** [comment]
Well that was what I thought to, but zypper slaped my fingers terrible.

```
[defaultuser@JollaC2 ~]$ devel-su zypper rm ffmpeg
Password: 
Reading installed packages...
Resolving package dependencies...

Problem: This request will break your system!
  This request will break your system!
This request will break your system!
This request will break your system!
This request will break your system!
This request will break your system!
This request will break your system!
the installed patterns-sailfish-core-device-1.1.32-1.14.1.jolla.noarch requires 'patterns-sailfish-mw', but this requirement cannot be provided
deleted providers: patterns-sailfish-mw-1.1.32-1.14.1.jolla.noarch
 Solution 1: Following actions will be done:
  ignore the warning of a broken system (requires:droid-config-s19mps)
  ignore the warning of a broken system (requires:mce)
  ignore the warning of a broken system (requires:dsme)
  ignore the warning of a broken system (requires:feature-jolla)
  ignore the warning of a broken system (requires:droid-hal-version-s19mps)
  ignore the warning of a broken system (requires:jolla-common-configurations)
  ignore the warning of a broken system (requires:patterns-sailfish-core-device)
 Solution 2: keep ffmpeg-5.1.6+git1-1.10.3.jolla.aarch64
 Solution 3: break patterns-sailfish-core-device-1.1.32-1.14.1.jolla.noarch by ignoring some of its dependencies

Choose from above solutions by number or cancel [1/2/3/c/d/?] (c): 2
Resolving dependencies...
Resolving package dependencies...
Nothing to do.
```

**Comment by eson57** [comment]
I wonder, where can I find ffmpeg? Can't find it in Chum.

**Comment by eson57** [comment]
Well, I think I give up for now. Something must be wrong with my C2 system even though I've hardly used it.
I can use Audacity on my desktop, so sorry to have bothered you with this shit.

**Comment by poetaster** [comment]
Yeah, it's not in chum and openrepos is a pain. try

zypper in --no-recommends --download-in-advance -f $(rpm -qa ffmpeg --qf '%{NAME} ')

That should install again and then you can check if it's really there by typing
which ffmpeg

or just running ffmpeg in the terminal

**Comment by eson57** [comment]
Nice try, still not there though.
